//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PagaReconDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.PagaReconData>
    {
    
        public PagaReconDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).PagaReconData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PagaReconDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.PagaReconData>
    {
        public PagaReconDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ImportedFile> ImportedFilesUnreconciled(global::System.Nullable<int> ReconSourcce)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ImportedFile> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.ImportedFile>("ImportedFiles"),
                (i) => ((i.ReconSummary.ID < 1) && (ReconSourcce.HasValue && (i.FileDefinition.ReconSource.ID == ReconSourcce))));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.FileDefinition))
            {
                return new global::LightSwitchApplication.Implementation.FileDefinition();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.FileField))
            {
                return new global::LightSwitchApplication.Implementation.FileField();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.FileSection))
            {
                return new global::LightSwitchApplication.Implementation.FileSection();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.FileType))
            {
                return new global::LightSwitchApplication.Implementation.FileType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ImportedFile))
            {
                return new global::LightSwitchApplication.Implementation.ImportedFile();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconDetail))
            {
                return new global::LightSwitchApplication.Implementation.ReconDetail();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconItemStatu))
            {
                return new global::LightSwitchApplication.Implementation.ReconItemStatu();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconProcess))
            {
                return new global::LightSwitchApplication.Implementation.ReconProcess();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconProcessStep))
            {
                return new global::LightSwitchApplication.Implementation.ReconProcessStep();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconSource))
            {
                return new global::LightSwitchApplication.Implementation.ReconSource();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconSourceType))
            {
                return new global::LightSwitchApplication.Implementation.ReconSourceType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconStatu))
            {
                return new global::LightSwitchApplication.Implementation.ReconStatu();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconSummary))
            {
                return new global::LightSwitchApplication.Implementation.ReconSummary();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ReconType))
            {
                return new global::LightSwitchApplication.Implementation.ReconType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.SkyeImportDetail))
            {
                return new global::LightSwitchApplication.Implementation.SkyeImportDetail();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.SkyeImportHeader))
            {
                return new global::LightSwitchApplication.Implementation.SkyeImportHeader();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.SystemField))
            {
                return new global::LightSwitchApplication.Implementation.SystemField();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.GlobalSetting))
            {
                return new global::LightSwitchApplication.Implementation.GlobalSetting();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.PagaReconData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.PagaReconData(this.GetEntityConnectionString(
                "PagaReconData",
                "res://" + assemblyName + "/PagaReconData.csdl|res://" + assemblyName + "/PagaReconData.ssdl|res://" + assemblyName + "/PagaReconData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.FileDefinition))
            {
                return new global::LightSwitchApplication.Implementation.FileDefinition();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FileField))
            {
                return new global::LightSwitchApplication.Implementation.FileField();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FileSection))
            {
                return new global::LightSwitchApplication.Implementation.FileSection();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FileType))
            {
                return new global::LightSwitchApplication.Implementation.FileType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ImportedFile))
            {
                return new global::LightSwitchApplication.Implementation.ImportedFile();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconDetail))
            {
                return new global::LightSwitchApplication.Implementation.ReconDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconItemStatu))
            {
                return new global::LightSwitchApplication.Implementation.ReconItemStatu();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconProcess))
            {
                return new global::LightSwitchApplication.Implementation.ReconProcess();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconProcessStep))
            {
                return new global::LightSwitchApplication.Implementation.ReconProcessStep();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconSource))
            {
                return new global::LightSwitchApplication.Implementation.ReconSource();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconSourceType))
            {
                return new global::LightSwitchApplication.Implementation.ReconSourceType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconStatu))
            {
                return new global::LightSwitchApplication.Implementation.ReconStatu();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconSummary))
            {
                return new global::LightSwitchApplication.Implementation.ReconSummary();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ReconType))
            {
                return new global::LightSwitchApplication.Implementation.ReconType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SkyeImportDetail))
            {
                return new global::LightSwitchApplication.Implementation.SkyeImportDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SkyeImportHeader))
            {
                return new global::LightSwitchApplication.Implementation.SkyeImportHeader();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SystemField))
            {
                return new global::LightSwitchApplication.Implementation.SystemField();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.GlobalSetting))
            {
                return new global::LightSwitchApplication.Implementation.GlobalSetting();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.PagaReconDataService))
            {
                return new global::LightSwitchApplication.PagaReconDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.PagaReconDataService))
            {
                return new global::LightSwitchApplication.Implementation.PagaReconDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.FileDefinition) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FileDefinition);
            }
            if (typeof(global::LightSwitchApplication.FileField) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FileField);
            }
            if (typeof(global::LightSwitchApplication.FileSection) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FileSection);
            }
            if (typeof(global::LightSwitchApplication.FileType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FileType);
            }
            if (typeof(global::LightSwitchApplication.ImportedFile) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ImportedFile);
            }
            if (typeof(global::LightSwitchApplication.ReconDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconDetail);
            }
            if (typeof(global::LightSwitchApplication.ReconItemStatu) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconItemStatu);
            }
            if (typeof(global::LightSwitchApplication.ReconProcess) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconProcess);
            }
            if (typeof(global::LightSwitchApplication.ReconProcessStep) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconProcessStep);
            }
            if (typeof(global::LightSwitchApplication.ReconSource) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconSource);
            }
            if (typeof(global::LightSwitchApplication.ReconSourceType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconSourceType);
            }
            if (typeof(global::LightSwitchApplication.ReconStatu) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconStatu);
            }
            if (typeof(global::LightSwitchApplication.ReconSummary) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconSummary);
            }
            if (typeof(global::LightSwitchApplication.ReconType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ReconType);
            }
            if (typeof(global::LightSwitchApplication.SkyeImportDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SkyeImportDetail);
            }
            if (typeof(global::LightSwitchApplication.SkyeImportHeader) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SkyeImportHeader);
            }
            if (typeof(global::LightSwitchApplication.SystemField) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SystemField);
            }
            if (typeof(global::LightSwitchApplication.GlobalSetting) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.GlobalSetting);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FileDefinition :
        global::LightSwitchApplication.FileDefinition.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FileDefinition.DetailsClass.IImplementation.FileType
        {
            get
            {
                return this.FileType;
            }
            set
            {
                this.FileType = (global::LightSwitchApplication.Implementation.FileType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("FileType");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.FileDefinition.DetailsClass.IImplementation.FileSections
        {
            get
            {
                return this.FileSections;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.FileDefinition.DetailsClass.IImplementation.ImportedFiles
        {
            get
            {
                return this.ImportedFiles;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FileDefinition.DetailsClass.IImplementation.ReconSource
        {
            get
            {
                return this.ReconSource;
            }
            set
            {
                this.ReconSource = (global::LightSwitchApplication.Implementation.ReconSource)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconSource");
                }
            }
        }
        
        partial void OnFileTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("FileType");
            }
        }
        
        partial void OnReconSourceIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconSource");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FileField :
        global::LightSwitchApplication.FileField.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FileField.DetailsClass.IImplementation.FileSection
        {
            get
            {
                return this.FileSection;
            }
            set
            {
                this.FileSection = (global::LightSwitchApplication.Implementation.FileSection)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("FileSection");
                }
            }
        }
        
        partial void OnFileSectionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("FileSection");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FileSection :
        global::LightSwitchApplication.FileSection.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.FileSection.DetailsClass.IImplementation.FileFields
        {
            get
            {
                return this.FileFields;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FileSection.DetailsClass.IImplementation.FileDefinition
        {
            get
            {
                return this.FileDefinition;
            }
            set
            {
                this.FileDefinition = (global::LightSwitchApplication.Implementation.FileDefinition)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("FileDefinition");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.FileSection.DetailsClass.IImplementation.ReconProcessSteps
        {
            get
            {
                return this.ReconProcessSteps;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.FileSection.DetailsClass.IImplementation.ReconProcessSteps1
        {
            get
            {
                return this.ReconProcessSteps1;
            }
        }
        
        partial void OnFileDefinitionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("FileDefinition");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FileType :
        global::LightSwitchApplication.FileType.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.FileType.DetailsClass.IImplementation.FileDefinitions
        {
            get
            {
                return this.FileDefinitions;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ImportedFile :
        global::LightSwitchApplication.ImportedFile.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ImportedFile.DetailsClass.IImplementation.FileDefinition
        {
            get
            {
                return this.FileDefinition;
            }
            set
            {
                this.FileDefinition = (global::LightSwitchApplication.Implementation.FileDefinition)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("FileDefinition");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ImportedFile.DetailsClass.IImplementation.ReconSummary
        {
            get
            {
                return this.ReconSummary;
            }
            set
            {
                this.ReconSummary = (global::LightSwitchApplication.Implementation.ReconSummary)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconSummary");
                }
            }
        }
        
        partial void OnFileDefinitionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("FileDefinition");
            }
        }
        
        partial void OnReconSummaryIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconSummary");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconDetail :
        global::LightSwitchApplication.ReconDetail.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconItemStatu :
        global::LightSwitchApplication.ReconItemStatu.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconProcess :
        global::LightSwitchApplication.ReconProcess.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconProcess.DetailsClass.IImplementation.ReconProcessSteps
        {
            get
            {
                return this.ReconProcessSteps;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconProcessStep :
        global::LightSwitchApplication.ReconProcessStep.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconProcessStep.DetailsClass.IImplementation.FileSection
        {
            get
            {
                return this.FileSection;
            }
            set
            {
                this.FileSection = (global::LightSwitchApplication.Implementation.FileSection)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("FileSection");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconProcessStep.DetailsClass.IImplementation.FileSection1
        {
            get
            {
                return this.FileSection1;
            }
            set
            {
                this.FileSection1 = (global::LightSwitchApplication.Implementation.FileSection)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("FileSection1");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconProcessStep.DetailsClass.IImplementation.ReconProcess
        {
            get
            {
                return this.ReconProcess;
            }
            set
            {
                this.ReconProcess = (global::LightSwitchApplication.Implementation.ReconProcess)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconProcess");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconProcessStep.DetailsClass.IImplementation.ReconType
        {
            get
            {
                return this.ReconType;
            }
            set
            {
                this.ReconType = (global::LightSwitchApplication.Implementation.ReconType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconType");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconProcessStep.DetailsClass.IImplementation.ReconSummaries
        {
            get
            {
                return this.ReconSummaries;
            }
        }
        
        partial void OnSourceFileSectionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("FileSection");
            }
        }
        
        partial void OnTargetFileSectionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("FileSection1");
            }
        }
        
        partial void OnReconProcessIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconProcess");
            }
        }
        
        partial void OnReconTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconSource :
        global::LightSwitchApplication.ReconSource.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconSource.DetailsClass.IImplementation.ReconSourceType
        {
            get
            {
                return this.ReconSourceType;
            }
            set
            {
                this.ReconSourceType = (global::LightSwitchApplication.Implementation.ReconSourceType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconSourceType");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconSource.DetailsClass.IImplementation.FileDefinitions
        {
            get
            {
                return this.FileDefinitions;
            }
        }
        
        partial void OnReconSourceTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconSourceType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconSourceType :
        global::LightSwitchApplication.ReconSourceType.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconSourceType.DetailsClass.IImplementation.ReconSources
        {
            get
            {
                return this.ReconSources;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconStatu :
        global::LightSwitchApplication.ReconStatu.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconStatu.DetailsClass.IImplementation.ReconSummaries
        {
            get
            {
                return this.ReconSummaries;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconSummary :
        global::LightSwitchApplication.ReconSummary.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconSummary.DetailsClass.IImplementation.ImportedFiles
        {
            get
            {
                return this.ImportedFiles;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconSummary.DetailsClass.IImplementation.ReconProcessStep
        {
            get
            {
                return this.ReconProcessStep;
            }
            set
            {
                this.ReconProcessStep = (global::LightSwitchApplication.Implementation.ReconProcessStep)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconProcessStep");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ReconSummary.DetailsClass.IImplementation.ReconStatu
        {
            get
            {
                return this.ReconStatu;
            }
            set
            {
                this.ReconStatu = (global::LightSwitchApplication.Implementation.ReconStatu)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ReconStatu");
                }
            }
        }
        
        partial void OnReconProcessStepIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconProcessStep");
            }
        }
        
        partial void OnReconStatusIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ReconStatu");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ReconType :
        global::LightSwitchApplication.ReconType.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ReconType.DetailsClass.IImplementation.ReconProcessSteps
        {
            get
            {
                return this.ReconProcessSteps;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SkyeImportDetail :
        global::LightSwitchApplication.SkyeImportDetail.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SkyeImportHeader :
        global::LightSwitchApplication.SkyeImportHeader.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SystemField :
        global::LightSwitchApplication.SystemField.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class GlobalSetting :
        global::LightSwitchApplication.GlobalSetting.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

