CREATE TABLE [Errors].[Activity_FactProcessTx] (
    [QueueID]                                INT             NOT NULL,
    [SSISErrorCode]                          INT             NOT NULL,
    [SSISErrorColumn]                        INT             NOT NULL,
    [PackageName]                            VARCHAR (255)   NOT NULL,
    [ErrorType]                              VARCHAR (255)   NOT NULL,
    [AgentCommissionAmount]                  DECIMAL (18, 2) NULL,
    [ATMReferenceNumber]                     VARCHAR (200)   NULL,
    [CardProcessorName]                      VARCHAR (200)   NULL,
    [change_operation]                       CHAR (1)        NOT NULL,
    [CustomerBillerAccount]                  VARCHAR (200)   NULL,
    [CustomerPhoneNumber]                    VARCHAR (200)   NULL,
    [DependentFactProcessTxSourceKey]        INT             NULL,
    [DepositNumber]                          VARCHAR (200)   NULL,
    [DimAgentCommissionTypeSourceKey]        VARCHAR (255)   NULL,
    [DimApprovedByUserSourceKey]             VARCHAR (255)   NULL,
    [DimCancellationApprovedByUserSourceKey] VARCHAR (255)   NULL,
    [DimChannelSourceKey]                    VARCHAR (255)   NOT NULL,
    [DimCompletedDateID]                     INT             NULL,
    [DimCompletedTimeID]                     INT             NULL,
    [DimCreatedDateID]                       INT             NOT NULL,
    [DimCreatedTimeID]                       INT             NOT NULL,
    [DimInitiatingUserSourceKey]             VARCHAR (255)   NULL,
    [DimOnBehalffUserSourceKey]              VARCHAR (255)   NULL,
    [DimProcessStatusSourceKey]              VARCHAR (255)   NOT NULL,
    [DimProcessTypeSourceKey]                VARCHAR (255)   NOT NULL,
    [DimReceivingUserSourceKey]              VARCHAR (255)   NULL,
    [DimStartedDateID]                       INT             NOT NULL,
    [DimStartedTimeID]                       INT             NOT NULL,
    [DimVerifiedByUserSourceKey]             VARCHAR (255)   NULL,
    [IntegrationReferenceNumber]             VARCHAR (200)   NULL,
    [LinkedPhoneNumber]                      VARCHAR (200)   NULL,
    [MerchantConfirmationCode]               VARCHAR (200)   NULL,
    [MerchantCustomerAccountNumber]          VARCHAR (200)   NULL,
    [OriginalFactProcessTxSourceKey]         INT             NULL,
    [PaymentSource]                          VARCHAR (200)   NULL,
    [ProcessAmount]                          DECIMAL (18, 2) NULL,
    [ProcessCode]                            VARCHAR (36)    NOT NULL,
    [ProcessFee]                             DECIMAL (18, 2) NULL,
    [ReferenceNumber]                        VARCHAR (200)   NULL,
    [SenderPhoneNumber]                      VARCHAR (200)   NULL,
    [SourceKey]                              INT             NOT NULL,
    [VerificationStatus]                     VARCHAR (200)   NULL,
    [WithdrawalCode]                         VARCHAR (200)   NULL
);

