CREATE TABLE [Shared].[FactProcessEvent] (
    [FactProcessEventID]          INT             IDENTITY (1, 1) NOT NULL,
    [SourceKey]                   INT             NOT NULL,
    [Name]                        VARCHAR (255)   NULL,
    [DimProcessTypeID]            INT             NULL,
	[DimUserID]                   INT             NULL,
    [DimForUserID]                INT             NULL,
    [DimToUserID]                 INT             NULL,
    [DimInitiatingUserID]         INT             NULL,
    [DimProcessChannelID]         INT             NOT NULL,
    [DimOriginalProcessChannelID] INT             NULL,
    [DimProcessStatusID]          INT             NULL,
    [HasFinancialTransaction]     BIT             NULL,
    [DimCompletedDateID]          INT             NULL,
    [DimCompletedTimeID]          INT             NULL,
    [ProcessAmount]               DECIMAL (18, 2) NULL,
    [ProcessFee]                  DECIMAL (18, 2) NULL,
	[DimAgentCommissionTypeID] [int] SPARSE  NULL,
	[AgentCommissionAmount] [decimal](18, 2) SPARSE  NULL,
	[ProcessCode] [varchar](36) NOT NULL,
	[WithdrawalCode] [varchar](200) SPARSE  NULL,
	[ATMReferenceNumber] [varchar](200) SPARSE  NULL,
	[CardProcessorName] [varchar](200) SPARSE  NULL,
	[CustomerBillerAccount] [varchar](200) SPARSE  NULL,
	[CustomerPhoneNumber] [varchar](200) SPARSE  NULL,
	[DepositNumber] [varchar](200) SPARSE  NULL,
	[LinkedPhoneNumber] [varchar](200) SPARSE  NULL,
	[MerchantConfirmationCode] [varchar](200) SPARSE  NULL,
	[MerchantCustomerAccountNumber] [varchar](200) SPARSE  NULL,
	[PaymentSource] [varchar](200) SPARSE  NULL,
	[ReferenceNumber] [varchar](200) SPARSE  NULL,
	[SenderPhoneNumber] [varchar](200) SPARSE  NULL,
	[DependentFactProcessTxID] [int] SPARSE  NULL,
	[OriginalFactProcessTxID] [int] SPARSE  NULL,
	[VerificationStatus] [varchar](200) SPARSE  NULL,
	[DimApprovedByUserID] [int] SPARSE  NULL,
	[DimVerifiedByUserID] [int] SPARSE  NULL,
	[DimCancellationApprovedByUserID] [int] SPARSE  NULL,
	[IntegrationReferenceNumber] [varchar](200) SPARSE  NULL,
    [SourceKeyHash]               BIGINT          NULL,
    [DeltaHash]                   BIGINT          NULL,
    [sys_CreatedBy]               VARCHAR (255)   DEFAULT (user_name()) NOT NULL,
    [sys_CreatedOn]               DATETIME        DEFAULT (getdate()) NOT NULL,
    [sys_ModifiedBy]              VARCHAR (255)   DEFAULT (user_name()) NOT NULL,
    [sys_ModifiedOn]              DATETIME        DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [pk_FactProcessEvent] PRIMARY KEY CLUSTERED ([FactProcessEventID] ASC)
);

