CREATE TABLE [dbo].[Fact_ProcessEvent] (
    [FactProcessEventID]          INT             IDENTITY (1, 1) NOT NULL,
    [SourceKey]                   INT             NOT NULL,
    [Name]                        VARCHAR (255)   NULL,
    [DimProcessTypeID]            INT             NULL,
    [DimUserID]                   INT             NULL,
    [DimForUserID]                INT             NULL,
    [DimToUserID]                 INT             NULL,
    [DimInitiatingUserID]         INT             NULL,
    [DimProcessChannelID]         INT             NOT NULL,
    [DimOriginalProcessChannelID] INT             NULL,
    [DimProcessStatusID]          INT             NULL,
    [HasFinancialTransaction]     BIT             NULL,
    [DimCompletedDateID]          INT             NULL,
    [DimCompletedTimeID]          INT             NULL,
    [ProcessAmount]               DECIMAL (18, 2) NULL,
    [ProcessFee]                  DECIMAL (18, 2) NULL,
    [SourceKeyHash]               BIGINT          NULL,
    [DeltaHash]                   BIGINT          NULL,
    [sys_CreatedBy]               VARCHAR (255)   DEFAULT (user_name()) NOT NULL,
    [sys_CreatedOn]               DATETIME        DEFAULT (getdate()) NOT NULL,
    [sys_ModifiedBy]              VARCHAR (255)   DEFAULT (user_name()) NOT NULL,
    [sys_ModifiedOn]              DATETIME        DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [pk_FactProcessEvent] PRIMARY KEY CLUSTERED ([FactProcessEventID] ASC)
);

