USE [Paga_EDW]
GO

SELECT 
'ALTER TABLE ['+TABLE_SCHEMA +'].[' +TABLE_NAME +'] 
ADD  CONSTRAINT [uc_' +TABLE_NAME +'_SourceKey] 
UNIQUE NONCLUSTERED 
(
	[SourceKey] ASC

);
GO'


FROM INFORMATION_SCHEMA.COLUMNS
WHERE 
	COLUMN_NAME = 'SourceKey'
	AND TABLE_SCHEMA <> 'OLAP'