SELECT
	TABLE_SCHEMA,
	TABLE_NAME,
	COLUMN_NAME,
	COALESCE(REF_SCHEMA, 'No Matching Schema'),
	REF_TABLE,
	COALESCE(CodeSnippet,'') AS CodeSnippet
FROM
(
	SELECT 
		missing.TABLE_SCHEMA,
		missing.TABLE_NAME,
		missing.COLUMN_NAME,
		ref.REF_SCHEMA,
		missing.REF_TABLE
	FROM 
	(
		SELECT 
		isc.TABLE_SCHEMA,
		isc.TABLE_NAME,
		isc.COLUMN_NAME,
		--'FactFinancialTransactions' AS REF_TABLE,
		REPLACE(isc.COLUMN_NAME,'ID','') AS REF_TABLE,
		kcu.CONSTRAINT_NAME
		FROM INFORMATION_SCHEMA.COLUMNS AS isc
		LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu ON
			isc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
			AND isc.TABLE_NAME = kcu.TABLE_NAME
			AND isc.COLUMN_NAME = kcu.COLUMN_NAME
		WHERE 
			isc.COLUMN_NAME LIKE '%ID'
			AND isc.TABLE_SCHEMA <> 'OLAP'
			AND kcu.CONSTRAINT_NAME IS NULL
	) as missing
	OUTER APPLY
	(
		SELECT
			TABLE_SCHEMA AS REF_SCHEMA
		FROM INFORMATION_SCHEMA.TABLES
		WHERE 
			TABLE_NAME = missing.REF_TABLE
			AND TABLE_SCHEMA <> 'OLAP'
	) AS REF
) _Param
CROSS APPLY master.dbo.AddForeignKey 
(
	_param.TABLE_SCHEMA,
	_param.TABLE_NAME,
	_Param.COLUMN_NAME,
	_param.REF_SCHEMA,
	_Param.REF_TABLE
)