CREATE TABLE [Errors].[DimProcessEvent] (
    [QueueID]                          INT           NOT NULL,
    [SSISErrorCode]                    INT           NOT NULL,
    [SSISErrorColumn]                  INT           NOT NULL,
    [PackageName]                      VARCHAR (255) NOT NULL,
    [ErrorType]                        VARCHAR (255) NOT NULL,
    [DimCompletedDateID]               INT           NULL,
    [DimCompletedTimeID]               INT           NULL,
    [FinancialTx_SourceKey]            INT           NULL,
    [ForUser_SourceKey]                INT           NULL,
    [HasFinancialTransaction]          BIT           NULL,
    [InitiatorUser_SourceKey]          INT           NULL,
    [OriginalProcessChannel_SourceKey] VARCHAR (50)  NULL,
    [ProcessChannel_SourceKey]         VARCHAR (8)   NOT NULL,
    [ProcessStatus_SourceKey]          VARCHAR (50)  NULL,
    [ProcessType_SourceKey]            VARCHAR (50)  NULL,
    [SourceKey]                        INT           NOT NULL,
    [ToUser_SourceKey]                 INT           NULL,
    [User_SourceKey]                   INT           NULL,
    [DeltaHash]                        BIGINT        NULL,
    [DimProcessEventID]                INT           NULL,
    [Name]                             VARCHAR (255) NULL,
    [SourceKeyHash]                    BIGINT        NULL,
    [DimForUserID]                     INT           NULL,
    [DimInitiatingUserID]              INT           NULL,
    [DimOriginalProcessChannelID]      INT           NULL,
    [DimProcessChannelID]              INT           NULL,
    [DimProcessStatusID]               INT           NULL,
    [DimProcessTypeID]                 INT           NULL,
    [DimToUserID]                      INT           NULL,
    [DimUserID]                        INT           NULL
);

