CREATE TABLE [Errors].[FactFinancialTransaction] (
    [QueueID]                       INT             NOT NULL,
    [SSISErrorCode]                 INT             NOT NULL,
    [SSISErrorColumn]               INT             NOT NULL,
    [PackageName]                   VARCHAR (255)   NOT NULL,
    [ErrorType]                     VARCHAR (255)   NOT NULL,
    [Cancelled]                     INT             NULL,
    [Currency_SourceKey]            VARCHAR (50)    NULL,
    [DimEffectiveDateID]            INT             NULL,
    [DimEffectiveTimeID]            INT             NULL,
    [DimFinancialTxDateID]          INT             NULL,
    [DimFinancialTxTimeID]          INT             NULL,
    [ExchangeRate]                  DECIMAL (16, 4) NULL,
    [ExternalReferenceNumber]       VARCHAR (100)   NULL,
    [FactIntegrationTx_SourceKey]   INT             NULL,
    [FinancialTx_Amount]            DECIMAL (18, 2) NULL,
    [FinancialTx_Fee]               DECIMAL (18, 2) NULL,
    [FinancialTxSubType_SourceKey]  VARCHAR (50)    NULL,
    [FinancialTxType_SourceKey]     VARCHAR (50)    NULL,
    [ForeignCurrencyAmount]         DECIMAL (18, 2) NULL,
    [IsIntegrationTx]               BIT             NULL,
    [OriginalFinancialTx_SourceKey] INT             NULL,
    [ProcessEvent_SourceKey]        INT             NULL,
    [ReferenceNumber]               VARCHAR (50)    NULL,
    [RelatedFinancialTx_SourceKey]  INT             NULL,
    [Reversed]                      BIT             NOT NULL,
    [ShortCode]                     VARCHAR (10)    NULL,
    [SourceKey]                     INT             NOT NULL,
    [TextDescription]               VARCHAR (100)   NULL,
    [User_SourceKey]                INT             NULL,
    [DeltaHash]                     BIGINT          NULL,
    [FactFinancialTxID]             INT             NULL,
    [FactIntegrationTxID]           INT             NULL,
    [SourceKeyHash]                 BIGINT          NULL,
    [DimCurrencyID]                 INT             NULL,
    [DimFinancialTxTypeID]          INT             NULL,
    [DimProcessEventID]             INT             NULL,
    [DimUserID]                     INT             NULL,
    [FactOriginalFinancialTxID]     INT             NULL,
    [FactRelatedFinancialTxID]      INT             NULL
);

