CREATE TABLE [Errors].[FactIntegrationTransaction] (
    [QueueID]                        INT             NOT NULL,
    [SSISErrorCode]                  INT             NOT NULL,
    [SSISErrorColumn]                INT             NOT NULL,
    [PackageName]                    VARCHAR (255)   NOT NULL,
    [ErrorType]                      VARCHAR (255)   NOT NULL,
    [DimIntegrationTxDateID]         INT             NULL,
    [DimIntegrationTxTimeID]         INT             NULL,
    [ExternalOrganization_Name]      VARCHAR (300)   NULL,
    [ExternalOrganization_SourceKey] VARCHAR (300)   NULL,
    [ExternalReferenceNumber]        VARCHAR (50)    NULL,
    [FinancialTransaction_SourceKey] INT             NULL,
    [HasFinancialTransaction]        BIT             NULL,
    [IntegrationTxAmount]            DECIMAL (18, 2) NULL,
    [IntegrationTxResult_SourceKey]  VARCHAR (50)    NULL,
    [IntegrationTxType_SourceKey]    VARCHAR (50)    NULL,
    [Message]                        VARCHAR (300)   NULL,
    [ProcessType_SourceKey]          VARCHAR (50)    NULL,
    [SourceKey]                      INT             NOT NULL,
    [User_SourceKey]                 INT             NULL,
    [DeltaHash]                      BIGINT          NULL,
    [FactIntegrationTxID]            INT             NULL,
    [HasFinancialTx]                 INT             NULL,
    [IntegrationTx_Amount]           DECIMAL (18, 2) NULL,
    [SourceKeyHash]                  BIGINT          NULL,
    [DimExternalOrganizationID]      INT             NULL,
    [DimIntegrationTxResultID]       INT             NULL,
    [DimIntegrationTxTypeID]         INT             NULL,
    [DimProcessTypeID]               INT             NULL,
    [DimUserID]                      INT             NULL,
    [FactFinancialTxID]              INT             NULL
);

