/*
Deployment script for paga_change_log

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "paga_change_log"
:setvar DefaultFilePrefix "paga_change_log"
:setvar DefaultDataPath "C:\sqlData\"
:setvar DefaultLogPath "C:\sqlLogs\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [dbo].[AccountCode]...';


GO
CREATE TABLE [dbo].[AccountCode] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [AccountCodeId]               INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[AccountCode].[ix_AccountCode_AccountCodeId]...';


GO
CREATE CLUSTERED INDEX [ix_AccountCode_AccountCodeId]
    ON [dbo].[AccountCode]([AccountCodeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[AccountCodeGroup]...';


GO
CREATE TABLE [dbo].[AccountCodeGroup] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [AccountCodeGroupId]          INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[AccountCodeGroup].[ix_AccountCodeGroup_AccountCodeGroupId]...';


GO
CREATE CLUSTERED INDEX [ix_AccountCodeGroup_AccountCodeGroupId]
    ON [dbo].[AccountCodeGroup]([AccountCodeGroupId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[AgentCommissionType]...';


GO
CREATE TABLE [dbo].[AgentCommissionType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [AgentCommissionTypeId]       VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[AgentCommissionType].[ix_AgentCommissionType_AgentCommissionTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_AgentCommissionType_AgentCommissionTypeId]
    ON [dbo].[AgentCommissionType]([AgentCommissionTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Bank]...';


GO
CREATE TABLE [dbo].[Bank] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [BankId]                      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Bank].[ix_Bank_BankId]...';


GO
CREATE CLUSTERED INDEX [ix_Bank_BankId]
    ON [dbo].[Bank]([BankId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[BankAccount]...';


GO
CREATE TABLE [dbo].[BankAccount] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [BankAccountId]               INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[BankAccount].[ix_BankAccount_BankAccountId]...';


GO
CREATE CLUSTERED INDEX [ix_BankAccount_BankAccountId]
    ON [dbo].[BankAccount]([BankAccountId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[BusinessType]...';


GO
CREATE TABLE [dbo].[BusinessType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [BusinessTypeId]              VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[BusinessType].[ix_BusinessType_BusinessTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_BusinessType_BusinessTypeId]
    ON [dbo].[BusinessType]([BusinessTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[City]...';


GO
CREATE TABLE [dbo].[City] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [CityId]                      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[City].[ix_City_CityId]...';


GO
CREATE CLUSTERED INDEX [ix_City_CityId]
    ON [dbo].[City]([CityId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Country]...';


GO
CREATE TABLE [dbo].[Country] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [CountryId]                   INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Country].[ix_Country_CountryId]...';


GO
CREATE CLUSTERED INDEX [ix_Country_CountryId]
    ON [dbo].[Country]([CountryId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Currency]...';


GO
CREATE TABLE [dbo].[Currency] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [CurrencyId]                  VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Currency].[ix_Currency_CurrencyId]...';


GO
CREATE CLUSTERED INDEX [ix_Currency_CurrencyId]
    ON [dbo].[Currency]([CurrencyId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialAccount]...';


GO
CREATE TABLE [dbo].[FinancialAccount] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [FinancialAccountId]          INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialAccount].[ix_FinancialAccount_FinancialAccountId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialAccount_FinancialAccountId]
    ON [dbo].[FinancialAccount]([FinancialAccountId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialAccountType]...';


GO
CREATE TABLE [dbo].[FinancialAccountType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [FinancialAccountTypeId]      VARCHAR (70)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialAccountType].[ix_FinancialAccountType_FinancialAccountTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialAccountType_FinancialAccountTypeId]
    ON [dbo].[FinancialAccountType]([FinancialAccountTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialTransaction]...';


GO
CREATE TABLE [dbo].[FinancialTransaction] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [FinancialTransactionId]      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialTransaction].[ix_FinancialTransaction_FinancialTransactionId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialTransaction_FinancialTransactionId]
    ON [dbo].[FinancialTransaction]([FinancialTransactionId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialTransactionItem]...';


GO
CREATE TABLE [dbo].[FinancialTransactionItem] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [FinancialTransactionItemId]  INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialTransactionItem].[ix_FinancialTransactionItem_FinancialTransactionItemId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialTransactionItem_FinancialTransactionItemId]
    ON [dbo].[FinancialTransactionItem]([FinancialTransactionItemId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialTransactionRelationship]...';


GO
CREATE TABLE [dbo].[FinancialTransactionRelationship] (
    [SYS_CHANGE_VERSION]                 BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]        BIGINT           NULL,
    [SYS_CHANGE_OPERATION]               NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                 VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]                 VARBINARY (128)  NULL,
    [FinancialTransactionRelationshipId] INT              NOT NULL,
    [sys_CreatedBy]                      VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                      DATETIME         NOT NULL,
    [row_id]                             INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialTransactionRelationship].[ix_FinancialTransactionRelationship_FinancialTransactionRelationshipId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialTransactionRelationship_FinancialTransactionRelationshipId]
    ON [dbo].[FinancialTransactionRelationship]([FinancialTransactionRelationshipId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialTransactionSubType]...';


GO
CREATE TABLE [dbo].[FinancialTransactionSubType] (
    [SYS_CHANGE_VERSION]            BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]   BIGINT           NULL,
    [SYS_CHANGE_OPERATION]          NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]            VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]            VARBINARY (128)  NULL,
    [FinancialTransactionSubTypeId] VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]                 VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                 DATETIME         NOT NULL,
    [row_id]                        INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialTransactionSubType].[ix_FinancialTransactionSubType_FinancialTransactionSubTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialTransactionSubType_FinancialTransactionSubTypeId]
    ON [dbo].[FinancialTransactionSubType]([FinancialTransactionSubTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialTransactionType]...';


GO
CREATE TABLE [dbo].[FinancialTransactionType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [FinancialTransactionTypeId]  VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialTransactionType].[ix_FinancialTransactionType_FinancialTransactionTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialTransactionType_FinancialTransactionTypeId]
    ON [dbo].[FinancialTransactionType]([FinancialTransactionTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[FinancialTransactionTypeTransactionTypeGroup]...';


GO
CREATE TABLE [dbo].[FinancialTransactionTypeTransactionTypeGroup] (
    [SYS_CHANGE_VERSION]                             BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]                    BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                           NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                             VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]                             VARBINARY (128)  NULL,
    [FinancialTransactionTypeTransactionTypeGroupId] INT              NOT NULL,
    [sys_CreatedBy]                                  VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                                  DATETIME         NOT NULL,
    [row_id]                                         INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[FinancialTransactionTypeTransactionTypeGroup].[ix_FinancialTransactionTypeTransactionTypeGroup_FinancialTransactionTypeTransactionTypeGroupId]...';


GO
CREATE CLUSTERED INDEX [ix_FinancialTransactionTypeTransactionTypeGroup_FinancialTransactionTypeTransactionTypeGroupId]
    ON [dbo].[FinancialTransactionTypeTransactionTypeGroup]([FinancialTransactionTypeTransactionTypeGroupId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Geozone]...';


GO
CREATE TABLE [dbo].[Geozone] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [GeozoneId]                   INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Geozone].[ix_Geozone_GeozoneId]...';


GO
CREATE CLUSTERED INDEX [ix_Geozone_GeozoneId]
    ON [dbo].[Geozone]([GeozoneId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[IntegrationTransaction]...';


GO
CREATE TABLE [dbo].[IntegrationTransaction] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [IntegrationTransactionId]    INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[IntegrationTransaction].[ix_IntegrationTransaction_IntegrationTransactionId]...';


GO
CREATE CLUSTERED INDEX [ix_IntegrationTransaction_IntegrationTransactionId]
    ON [dbo].[IntegrationTransaction]([IntegrationTransactionId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[LocalGovernmentArea]...';


GO
CREATE TABLE [dbo].[LocalGovernmentArea] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [LocalGovernmentAreaId]       INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[LocalGovernmentArea].[ix_LocalGovernmentArea_LocalGovernmentAreaId]...';


GO
CREATE CLUSTERED INDEX [ix_LocalGovernmentArea_LocalGovernmentAreaId]
    ON [dbo].[LocalGovernmentArea]([LocalGovernmentAreaId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[MerchantCategory]...';


GO
CREATE TABLE [dbo].[MerchantCategory] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [MerchantCategoryId]          VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[MerchantCategory].[ix_MerchantCategory_MerchantCategoryId]...';


GO
CREATE CLUSTERED INDEX [ix_MerchantCategory_MerchantCategoryId]
    ON [dbo].[MerchantCategory]([MerchantCategoryId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[MobileOperator]...';


GO
CREATE TABLE [dbo].[MobileOperator] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [MobileOperatorId]            INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[MobileOperator].[ix_MobileOperator_MobileOperatorId]...';


GO
CREATE CLUSTERED INDEX [ix_MobileOperator_MobileOperatorId]
    ON [dbo].[MobileOperator]([MobileOperatorId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Organization]...';


GO
CREATE TABLE [dbo].[Organization] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [OrganizationId]              INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Organization].[ix_Organization_OrganizationId]...';


GO
CREATE CLUSTERED INDEX [ix_Organization_OrganizationId]
    ON [dbo].[Organization]([OrganizationId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationMerchantCategory]...';


GO
CREATE TABLE [dbo].[OrganizationMerchantCategory] (
    [SYS_CHANGE_VERSION]             BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]    BIGINT           NULL,
    [SYS_CHANGE_OPERATION]           NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]             VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]             VARBINARY (128)  NULL,
    [OrganizationMerchantCategoryId] INT              NOT NULL,
    [sys_CreatedBy]                  VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                  DATETIME         NOT NULL,
    [row_id]                         INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationMerchantCategory].[ix_OrganizationMerchantCategory_OrganizationMerchantCategoryId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationMerchantCategory_OrganizationMerchantCategoryId]
    ON [dbo].[OrganizationMerchantCategory]([OrganizationMerchantCategoryId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationMerchantProcessChannel]...';


GO
CREATE TABLE [dbo].[OrganizationMerchantProcessChannel] (
    [SYS_CHANGE_VERSION]                   BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                 NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                   VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]                   VARBINARY (128)  NULL,
    [OrganizationMerchantProcessChannelId] INT              NOT NULL,
    [sys_CreatedBy]                        VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                        DATETIME         NOT NULL,
    [row_id]                               INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationMerchantProcessChannel].[ix_OrganizationMerchantProcessChannel_OrganizationMerchantProcessChannelId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationMerchantProcessChannel_OrganizationMerchantProcessChannelId]
    ON [dbo].[OrganizationMerchantProcessChannel]([OrganizationMerchantProcessChannelId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationSubscriptionStatus]...';


GO
CREATE TABLE [dbo].[OrganizationSubscriptionStatus] (
    [SYS_CHANGE_VERSION]               BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]      BIGINT           NULL,
    [SYS_CHANGE_OPERATION]             NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]               VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]               VARBINARY (128)  NULL,
    [OrganizationSubscriptionStatusId] VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]                    VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                    DATETIME         NOT NULL,
    [row_id]                           INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationSubscriptionStatus].[ix_OrganizationSubscriptionStatus_OrganizationSubscriptionStatusId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationSubscriptionStatus_OrganizationSubscriptionStatusId]
    ON [dbo].[OrganizationSubscriptionStatus]([OrganizationSubscriptionStatusId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationUnit]...';


GO
CREATE TABLE [dbo].[OrganizationUnit] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [OrganizationUnitId]          INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationUnit].[ix_OrganizationUnit_OrganizationUnitId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationUnit_OrganizationUnitId]
    ON [dbo].[OrganizationUnit]([OrganizationUnitId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationUnitType]...';


GO
CREATE TABLE [dbo].[OrganizationUnitType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [OrganizationUnitTypeId]      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationUnitType].[ix_OrganizationUnitType_OrganizationUnitTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationUnitType_OrganizationUnitTypeId]
    ON [dbo].[OrganizationUnitType]([OrganizationUnitTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationUnitUser]...';


GO
CREATE TABLE [dbo].[OrganizationUnitUser] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [OrganizationUnitUserId]      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationUnitUser].[ix_OrganizationUnitUser_OrganizationUnitUserId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationUnitUser_OrganizationUnitUserId]
    ON [dbo].[OrganizationUnitUser]([OrganizationUnitUserId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[OrganizationVerificationStatus]...';


GO
CREATE TABLE [dbo].[OrganizationVerificationStatus] (
    [SYS_CHANGE_VERSION]               BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]      BIGINT           NULL,
    [SYS_CHANGE_OPERATION]             NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]               VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]               VARBINARY (128)  NULL,
    [OrganizationVerificationStatusId] VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]                    VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]                    DATETIME         NOT NULL,
    [row_id]                           INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[OrganizationVerificationStatus].[ix_OrganizationVerificationStatus_OrganizationVerificationStatusId]...';


GO
CREATE CLUSTERED INDEX [ix_OrganizationVerificationStatus_OrganizationVerificationStatusId]
    ON [dbo].[OrganizationVerificationStatus]([OrganizationVerificationStatusId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[PagaAccount]...';


GO
CREATE TABLE [dbo].[PagaAccount] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [PagaAccountId]               INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[PagaAccount].[ix_PagaAccount_PagaAccountId]...';


GO
CREATE CLUSTERED INDEX [ix_PagaAccount_PagaAccountId]
    ON [dbo].[PagaAccount]([PagaAccountId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[PagaAccountNature]...';


GO
CREATE TABLE [dbo].[PagaAccountNature] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [PagaAccountNatureId]         INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[PagaAccountNature].[ix_PagaAccountNature_PagaAccountNatureId]...';


GO
CREATE CLUSTERED INDEX [ix_PagaAccountNature_PagaAccountNatureId]
    ON [dbo].[PagaAccountNature]([PagaAccountNatureId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[PagaAccountStatus]...';


GO
CREATE TABLE [dbo].[PagaAccountStatus] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [PagaAccountStatusId]         VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[PagaAccountStatus].[ix_PagaAccountStatus_PagaAccountStatusId]...';


GO
CREATE CLUSTERED INDEX [ix_PagaAccountStatus_PagaAccountStatusId]
    ON [dbo].[PagaAccountStatus]([PagaAccountStatusId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[PagaAccountUser]...';


GO
CREATE TABLE [dbo].[PagaAccountUser] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [PagaAccountUserId]           INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[PagaAccountUser].[ix_PagaAccountUser_PagaAccountUserId]...';


GO
CREATE CLUSTERED INDEX [ix_PagaAccountUser_PagaAccountUserId]
    ON [dbo].[PagaAccountUser]([PagaAccountUserId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[PagaAccountUserType]...';


GO
CREATE TABLE [dbo].[PagaAccountUserType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [PagaAccountUserTypeId]       VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[PagaAccountUserType].[ix_PagaAccountUserType_PagaAccountUserTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_PagaAccountUserType_PagaAccountUserTypeId]
    ON [dbo].[PagaAccountUserType]([PagaAccountUserTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Process]...';


GO
CREATE TABLE [dbo].[Process] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [ProcessId]                   INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Process].[ix_Process_ProcessId]...';


GO
CREATE CLUSTERED INDEX [ix_Process_ProcessId]
    ON [dbo].[Process]([ProcessId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[ProcessChannel]...';


GO
CREATE TABLE [dbo].[ProcessChannel] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [ProcessChannelId]            VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[ProcessChannel].[ix_ProcessChannel_ProcessChannelId]...';


GO
CREATE CLUSTERED INDEX [ix_ProcessChannel_ProcessChannelId]
    ON [dbo].[ProcessChannel]([ProcessChannelId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[ProcessData]...';


GO
CREATE TABLE [dbo].[ProcessData] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [ProcessDataId]               INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[ProcessData].[ix_ProcessData_ProcessDataId]...';


GO
CREATE CLUSTERED INDEX [ix_ProcessData_ProcessDataId]
    ON [dbo].[ProcessData]([ProcessDataId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[ProcessStatus]...';


GO
CREATE TABLE [dbo].[ProcessStatus] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [ProcessStatusId]             VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[ProcessStatus].[ix_ProcessStatus_ProcessStatusId]...';


GO
CREATE CLUSTERED INDEX [ix_ProcessStatus_ProcessStatusId]
    ON [dbo].[ProcessStatus]([ProcessStatusId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[ProcessType]...';


GO
CREATE TABLE [dbo].[ProcessType] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [ProcessTypeId]               VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[ProcessType].[ix_ProcessType_ProcessTypeId]...';


GO
CREATE CLUSTERED INDEX [ix_ProcessType_ProcessTypeId]
    ON [dbo].[ProcessType]([ProcessTypeId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[ProcessTypeGroup]...';


GO
CREATE TABLE [dbo].[ProcessTypeGroup] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [ProcessTypeGroupId]          VARCHAR (50)     NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[ProcessTypeGroup].[ix_ProcessTypeGroup_ProcessTypeGroupId]...';


GO
CREATE CLUSTERED INDEX [ix_ProcessTypeGroup_ProcessTypeGroupId]
    ON [dbo].[ProcessTypeGroup]([ProcessTypeGroupId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Region]...';


GO
CREATE TABLE [dbo].[Region] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [RegionId]                    INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Region].[ix_Region_RegionId]...';


GO
CREATE CLUSTERED INDEX [ix_Region_RegionId]
    ON [dbo].[Region]([RegionId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[RoleLookup]...';


GO
CREATE TABLE [dbo].[RoleLookup] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [RoleId]                      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[RoleLookup].[ix_RoleLookup_RoleId]...';


GO
CREATE CLUSTERED INDEX [ix_RoleLookup_RoleId]
    ON [dbo].[RoleLookup]([RoleId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[UserRole]...';


GO
CREATE TABLE [dbo].[UserRole] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [UserRoleId]                  INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[UserRole].[ix_UserRole_UserRoleId]...';


GO
CREATE CLUSTERED INDEX [ix_UserRole_UserRoleId]
    ON [dbo].[UserRole]([UserRoleId] ASC, [row_id] ASC);


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          VARBINARY (4100) NULL,
    [SYS_CHANGE_CONTEXT]          VARBINARY (128)  NULL,
    [UserId]                      INT              NOT NULL,
    [sys_CreatedBy]               VARCHAR (255)    NOT NULL,
    [sys_CreatedOn]               DATETIME         NOT NULL,
    [row_id]                      INT              IDENTITY (1, 1) NOT NULL
);


GO
PRINT N'Creating [dbo].[Users].[ix_Users_UserId]...';


GO
CREATE CLUSTERED INDEX [ix_Users_UserId]
    ON [dbo].[Users]([UserId] ASC, [row_id] ASC);


GO
PRINT N'Creating unnamed constraint on [dbo].[AccountCode]...';


GO
ALTER TABLE [dbo].[AccountCode]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[AccountCode]...';


GO
ALTER TABLE [dbo].[AccountCode]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[AccountCodeGroup]...';


GO
ALTER TABLE [dbo].[AccountCodeGroup]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[AccountCodeGroup]...';


GO
ALTER TABLE [dbo].[AccountCodeGroup]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[AgentCommissionType]...';


GO
ALTER TABLE [dbo].[AgentCommissionType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[AgentCommissionType]...';


GO
ALTER TABLE [dbo].[AgentCommissionType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Bank]...';


GO
ALTER TABLE [dbo].[Bank]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Bank]...';


GO
ALTER TABLE [dbo].[Bank]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[BankAccount]...';


GO
ALTER TABLE [dbo].[BankAccount]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[BankAccount]...';


GO
ALTER TABLE [dbo].[BankAccount]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[BusinessType]...';


GO
ALTER TABLE [dbo].[BusinessType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[BusinessType]...';


GO
ALTER TABLE [dbo].[BusinessType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[City]...';


GO
ALTER TABLE [dbo].[City]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[City]...';


GO
ALTER TABLE [dbo].[City]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Country]...';


GO
ALTER TABLE [dbo].[Country]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Country]...';


GO
ALTER TABLE [dbo].[Country]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Currency]...';


GO
ALTER TABLE [dbo].[Currency]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Currency]...';


GO
ALTER TABLE [dbo].[Currency]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialAccount]...';


GO
ALTER TABLE [dbo].[FinancialAccount]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialAccount]...';


GO
ALTER TABLE [dbo].[FinancialAccount]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialAccountType]...';


GO
ALTER TABLE [dbo].[FinancialAccountType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialAccountType]...';


GO
ALTER TABLE [dbo].[FinancialAccountType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransaction]...';


GO
ALTER TABLE [dbo].[FinancialTransaction]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransaction]...';


GO
ALTER TABLE [dbo].[FinancialTransaction]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionItem]...';


GO
ALTER TABLE [dbo].[FinancialTransactionItem]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionItem]...';


GO
ALTER TABLE [dbo].[FinancialTransactionItem]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionRelationship]...';


GO
ALTER TABLE [dbo].[FinancialTransactionRelationship]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionRelationship]...';


GO
ALTER TABLE [dbo].[FinancialTransactionRelationship]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionSubType]...';


GO
ALTER TABLE [dbo].[FinancialTransactionSubType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionSubType]...';


GO
ALTER TABLE [dbo].[FinancialTransactionSubType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionType]...';


GO
ALTER TABLE [dbo].[FinancialTransactionType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionType]...';


GO
ALTER TABLE [dbo].[FinancialTransactionType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionTypeTransactionTypeGroup]...';


GO
ALTER TABLE [dbo].[FinancialTransactionTypeTransactionTypeGroup]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[FinancialTransactionTypeTransactionTypeGroup]...';


GO
ALTER TABLE [dbo].[FinancialTransactionTypeTransactionTypeGroup]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Geozone]...';


GO
ALTER TABLE [dbo].[Geozone]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Geozone]...';


GO
ALTER TABLE [dbo].[Geozone]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[IntegrationTransaction]...';


GO
ALTER TABLE [dbo].[IntegrationTransaction]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[IntegrationTransaction]...';


GO
ALTER TABLE [dbo].[IntegrationTransaction]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[LocalGovernmentArea]...';


GO
ALTER TABLE [dbo].[LocalGovernmentArea]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[LocalGovernmentArea]...';


GO
ALTER TABLE [dbo].[LocalGovernmentArea]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[MerchantCategory]...';


GO
ALTER TABLE [dbo].[MerchantCategory]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[MerchantCategory]...';


GO
ALTER TABLE [dbo].[MerchantCategory]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[MobileOperator]...';


GO
ALTER TABLE [dbo].[MobileOperator]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[MobileOperator]...';


GO
ALTER TABLE [dbo].[MobileOperator]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Organization]...';


GO
ALTER TABLE [dbo].[Organization]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Organization]...';


GO
ALTER TABLE [dbo].[Organization]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationMerchantCategory]...';


GO
ALTER TABLE [dbo].[OrganizationMerchantCategory]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationMerchantCategory]...';


GO
ALTER TABLE [dbo].[OrganizationMerchantCategory]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationMerchantProcessChannel]...';


GO
ALTER TABLE [dbo].[OrganizationMerchantProcessChannel]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationMerchantProcessChannel]...';


GO
ALTER TABLE [dbo].[OrganizationMerchantProcessChannel]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationSubscriptionStatus]...';


GO
ALTER TABLE [dbo].[OrganizationSubscriptionStatus]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationSubscriptionStatus]...';


GO
ALTER TABLE [dbo].[OrganizationSubscriptionStatus]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationUnit]...';


GO
ALTER TABLE [dbo].[OrganizationUnit]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationUnit]...';


GO
ALTER TABLE [dbo].[OrganizationUnit]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationUnitType]...';


GO
ALTER TABLE [dbo].[OrganizationUnitType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationUnitType]...';


GO
ALTER TABLE [dbo].[OrganizationUnitType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationUnitUser]...';


GO
ALTER TABLE [dbo].[OrganizationUnitUser]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationUnitUser]...';


GO
ALTER TABLE [dbo].[OrganizationUnitUser]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationVerificationStatus]...';


GO
ALTER TABLE [dbo].[OrganizationVerificationStatus]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[OrganizationVerificationStatus]...';


GO
ALTER TABLE [dbo].[OrganizationVerificationStatus]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccount]...';


GO
ALTER TABLE [dbo].[PagaAccount]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccount]...';


GO
ALTER TABLE [dbo].[PagaAccount]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountNature]...';


GO
ALTER TABLE [dbo].[PagaAccountNature]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountNature]...';


GO
ALTER TABLE [dbo].[PagaAccountNature]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountStatus]...';


GO
ALTER TABLE [dbo].[PagaAccountStatus]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountStatus]...';


GO
ALTER TABLE [dbo].[PagaAccountStatus]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountUser]...';


GO
ALTER TABLE [dbo].[PagaAccountUser]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountUser]...';


GO
ALTER TABLE [dbo].[PagaAccountUser]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountUserType]...';


GO
ALTER TABLE [dbo].[PagaAccountUserType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[PagaAccountUserType]...';


GO
ALTER TABLE [dbo].[PagaAccountUserType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Process]...';


GO
ALTER TABLE [dbo].[Process]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Process]...';


GO
ALTER TABLE [dbo].[Process]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessChannel]...';


GO
ALTER TABLE [dbo].[ProcessChannel]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessChannel]...';


GO
ALTER TABLE [dbo].[ProcessChannel]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessData]...';


GO
ALTER TABLE [dbo].[ProcessData]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessData]...';


GO
ALTER TABLE [dbo].[ProcessData]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessStatus]...';


GO
ALTER TABLE [dbo].[ProcessStatus]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessStatus]...';


GO
ALTER TABLE [dbo].[ProcessStatus]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessType]...';


GO
ALTER TABLE [dbo].[ProcessType]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessType]...';


GO
ALTER TABLE [dbo].[ProcessType]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessTypeGroup]...';


GO
ALTER TABLE [dbo].[ProcessTypeGroup]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[ProcessTypeGroup]...';


GO
ALTER TABLE [dbo].[ProcessTypeGroup]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Region]...';


GO
ALTER TABLE [dbo].[Region]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Region]...';


GO
ALTER TABLE [dbo].[Region]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[RoleLookup]...';


GO
ALTER TABLE [dbo].[RoleLookup]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[RoleLookup]...';


GO
ALTER TABLE [dbo].[RoleLookup]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[UserRole]...';


GO
ALTER TABLE [dbo].[UserRole]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[UserRole]...';


GO
ALTER TABLE [dbo].[UserRole]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT (user_name()) FOR [sys_CreatedBy];


GO
PRINT N'Creating unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT (getdate()) FOR [sys_CreatedOn];


GO
PRINT N'Creating [dbo].[AccountCode].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			AccountCodeId = CAST(AccountCodeId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[AccountCode],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AccountCode';


GO
PRINT N'Creating [dbo].[AccountCodeGroup].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			AccountCodeGroupId = CAST(AccountCodeGroupId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[AccountCodeGroup],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AccountCodeGroup';


GO
PRINT N'Creating [dbo].[AgentCommissionType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			AgentCommissionTypeId = CAST(AgentCommissionTypeId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[AgentCommissionType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AgentCommissionType';


GO
PRINT N'Creating [dbo].[Bank].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			BankId = CAST(BankId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Bank],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Bank';


GO
PRINT N'Creating [dbo].[BankAccount].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			BankAccountId = CAST(BankAccountId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[BankAccount],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'BankAccount';


GO
PRINT N'Creating [dbo].[BusinessType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			BusinessTypeId = CAST(BusinessTypeId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[BusinessType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'BusinessType';


GO
PRINT N'Creating [dbo].[City].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			CityId = CAST(CityId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[City],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'City';


GO
PRINT N'Creating [dbo].[Country].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			CountryId = CAST(CountryId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Country],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Country';


GO
PRINT N'Creating [dbo].[Currency].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			CurrencyId = CAST(CurrencyId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[Currency],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Currency';


GO
PRINT N'Creating [dbo].[FinancialAccount].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialAccountId = CAST(FinancialAccountId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[FinancialAccount],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialAccount';


GO
PRINT N'Creating [dbo].[FinancialAccountType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialAccountTypeId = CAST(FinancialAccountTypeId AS varchar(70))
		FROM CHANGETABLE(CHANGES [dbo].[FinancialAccountType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialAccountType';


GO
PRINT N'Creating [dbo].[FinancialTransaction].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialTransactionId = CAST(FinancialTransactionId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[FinancialTransaction],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialTransaction';


GO
PRINT N'Creating [dbo].[FinancialTransactionItem].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialTransactionItemId = CAST(FinancialTransactionItemId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[FinancialTransactionItem],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialTransactionItem';


GO
PRINT N'Creating [dbo].[FinancialTransactionRelationship].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialTransactionRelationshipId = CAST(FinancialTransactionRelationshipId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[FinancialTransactionRelationship],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialTransactionRelationship';


GO
PRINT N'Creating [dbo].[FinancialTransactionSubType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialTransactionSubTypeId = CAST(FinancialTransactionSubTypeId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[FinancialTransactionSubType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialTransactionSubType';


GO
PRINT N'Creating [dbo].[FinancialTransactionType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialTransactionTypeId = CAST(FinancialTransactionTypeId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[FinancialTransactionType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialTransactionType';


GO
PRINT N'Creating [dbo].[FinancialTransactionTypeTransactionTypeGroup].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			FinancialTransactionTypeTransactionTypeGroupId = CAST(FinancialTransactionTypeTransactionTypeGroupId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[FinancialTransactionTypeTransactionTypeGroup],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FinancialTransactionTypeTransactionTypeGroup';


GO
PRINT N'Creating [dbo].[Geozone].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			GeozoneId = CAST(GeozoneId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Geozone],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Geozone';


GO
PRINT N'Creating [dbo].[IntegrationTransaction].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			IntegrationTransactionId = CAST(IntegrationTransactionId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[IntegrationTransaction],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'IntegrationTransaction';


GO
PRINT N'Creating [dbo].[LocalGovernmentArea].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			LocalGovernmentAreaId = CAST(LocalGovernmentAreaId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[LocalGovernmentArea],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'LocalGovernmentArea';


GO
PRINT N'Creating [dbo].[MerchantCategory].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			MerchantCategoryId = CAST(MerchantCategoryId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[MerchantCategory],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MerchantCategory';


GO
PRINT N'Creating [dbo].[MobileOperator].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			MobileOperatorId = CAST(MobileOperatorId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[MobileOperator],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MobileOperator';


GO
PRINT N'Creating [dbo].[Organization].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationId = CAST(OrganizationId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Organization],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Organization';


GO
PRINT N'Creating [dbo].[OrganizationMerchantCategory].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationMerchantCategoryId = CAST(OrganizationMerchantCategoryId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationMerchantCategory],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationMerchantCategory';


GO
PRINT N'Creating [dbo].[OrganizationMerchantProcessChannel].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationMerchantProcessChannelId = CAST(OrganizationMerchantProcessChannelId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationMerchantProcessChannel],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationMerchantProcessChannel';


GO
PRINT N'Creating [dbo].[OrganizationSubscriptionStatus].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationSubscriptionStatusId = CAST(OrganizationSubscriptionStatusId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationSubscriptionStatus],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationSubscriptionStatus';


GO
PRINT N'Creating [dbo].[OrganizationUnit].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationUnitId = CAST(OrganizationUnitId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationUnit],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationUnit';


GO
PRINT N'Creating [dbo].[OrganizationUnitType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationUnitTypeId = CAST(OrganizationUnitTypeId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationUnitType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationUnitType';


GO
PRINT N'Creating [dbo].[OrganizationUnitUser].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationUnitUserId = CAST(OrganizationUnitUserId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationUnitUser],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationUnitUser';


GO
PRINT N'Creating [dbo].[OrganizationVerificationStatus].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			OrganizationVerificationStatusId = CAST(OrganizationVerificationStatusId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[OrganizationVerificationStatus],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OrganizationVerificationStatus';


GO
PRINT N'Creating [dbo].[PagaAccount].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			PagaAccountId = CAST(PagaAccountId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[PagaAccount],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PagaAccount';


GO
PRINT N'Creating [dbo].[PagaAccountNature].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			PagaAccountNatureId = CAST(PagaAccountNatureId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[PagaAccountNature],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PagaAccountNature';


GO
PRINT N'Creating [dbo].[PagaAccountStatus].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			PagaAccountStatusId = CAST(PagaAccountStatusId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[PagaAccountStatus],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PagaAccountStatus';


GO
PRINT N'Creating [dbo].[PagaAccountUser].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			PagaAccountUserId = CAST(PagaAccountUserId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[PagaAccountUser],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PagaAccountUser';


GO
PRINT N'Creating [dbo].[PagaAccountUserType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			PagaAccountUserTypeId = CAST(PagaAccountUserTypeId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[PagaAccountUserType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PagaAccountUserType';


GO
PRINT N'Creating [dbo].[Process].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			ProcessId = CAST(ProcessId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Process],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Process';


GO
PRINT N'Creating [dbo].[ProcessChannel].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			ProcessChannelId = CAST(ProcessChannelId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[ProcessChannel],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProcessChannel';


GO
PRINT N'Creating [dbo].[ProcessData].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			ProcessDataId = CAST(ProcessDataId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[ProcessData],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProcessData';


GO
PRINT N'Creating [dbo].[ProcessStatus].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			ProcessStatusId = CAST(ProcessStatusId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[ProcessStatus],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProcessStatus';


GO
PRINT N'Creating [dbo].[ProcessType].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			ProcessTypeId = CAST(ProcessTypeId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[ProcessType],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProcessType';


GO
PRINT N'Creating [dbo].[ProcessTypeGroup].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			ProcessTypeGroupId = CAST(ProcessTypeGroupId AS varchar(50))
		FROM CHANGETABLE(CHANGES [dbo].[ProcessTypeGroup],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProcessTypeGroup';


GO
PRINT N'Creating [dbo].[Region].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			RegionId = CAST(RegionId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Region],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Region';


GO
PRINT N'Creating [dbo].[RoleLookup].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			RoleId = CAST(RoleId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[Role],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'RoleLookup';


GO
PRINT N'Creating [dbo].[UserRole].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			UserRoleId = CAST(UserRoleId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[UserRole],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'UserRole';


GO
PRINT N'Creating [dbo].[Users].[BaseQuery]...';


GO
EXECUTE sp_addextendedproperty @name = N'BaseQuery', @value = N'
		SET NOCOUNT ON;
		SELECT 
			SYS_CHANGE_VERSION,
			SYS_CHANGE_CREATION_VERSION,
			SYS_CHANGE_OPERATION,
			SYS_CHANGE_COLUMNS,
			SYS_CHANGE_CONTEXT,
			UserId = CAST(UserId AS int)
		FROM CHANGETABLE(CHANGES [dbo].[User],0)  AS change_log', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Users';


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
