CREATE TABLE [Staging].[FactProcessTransaction] (
    [FactProcessTransactionID]        INT             NULL,
    [AgentCommissionAmount]           DECIMAL (18, 2) NULL,
    [ATMReferenceNumber]              VARCHAR (255)   NULL,
    [CardProcessorName]               VARCHAR (255)   NULL,
    [CustomerBillerAccount]           VARCHAR (255)   NULL,
    [CustomerPhoneNumber]             VARCHAR (255)   NULL,
    [DependentProcessID]              INT             NULL,
    [DepositNumber]                   VARCHAR (255)   NULL,
    [DimOriginalPayerPagaAccountIDID] INT             NULL,
    [DimPagaAccountID]                INT             NULL,
    [LinkedPhoneNumber]               VARCHAR (255)   NULL,
    [MerchantConfirmationCode]        VARCHAR (255)   NULL,
    [MerchantCustomerAccountNumber]   VARCHAR (255)   NULL,
    [OriginalProcessID]               INT             NULL,
    [PaymentSource]                   VARCHAR (255)   NULL,
    [ProcessAmount]                   DECIMAL (18, 2) NULL,
    [ProcessFee]                      DECIMAL (18, 2) NULL,
    [ReferenceNumber]                 VARCHAR (255)   NULL,
    [RequestedProcessChannel]         VARCHAR (255)   NULL,
    [RunID]                           INT             NOT NULL,
    [SenderPhoneNumber]               VARCHAR (255)   NULL,
    [WithdrawalCode]                  VARCHAR (255)   NULL,
    [AgentCommissionTypeSourceKey]    VARCHAR (255)   NULL,
    [UserSourceKey]                   VARCHAR (255)   NULL,
    [ChannelSourceKey]                VARCHAR (255)   NULL,
    [CitySourceKey]                   VARCHAR (255)   NULL,
    [CreatedDateSourceKey]            VARCHAR (255)   NULL,
    [CreatedTimeSourceKey]            VARCHAR (255)   NULL,
    [StartedDateSourceKey]            VARCHAR (255)   NULL,
    [StartedTimeSourceKey]            VARCHAR (255)   NULL,
    [BillerAccountUserSourceKey]      VARCHAR (255)   NULL,
    [OrganizationSourceKey]           VARCHAR (255)   NULL,
    [OrganizationUnitLevel5SourceKey] VARCHAR (255)   NULL,
    [ProcessStatusSourceKey]          VARCHAR (255)   NULL,
    [ProcessTypeSourceKey]            VARCHAR (255)   NULL,
    [ApprovedByUserSourceKey]         VARCHAR (255)   NULL,
    [TransferDateSourceKey]           VARCHAR (255)   NULL,
    [TransferTimeSourceKey]           VARCHAR (255)   NULL,
    [CompletedDateSourceKey]          VARCHAR (255)   NULL,
    [CompletedTimeSourceKey]          VARCHAR (255)   NULL,
    [VerifiedByUserSourceKey]         VARCHAR (255)   NULL
);

