CREATE TABLE [Errors].[Finance_FactFinancialTransaction] (
    [QueueID]                      INT             NOT NULL,
    [SSISErrorCode]                INT             NOT NULL,
    [SSISErrorColumn]              INT             NOT NULL,
    [PackageName]                  VARCHAR (255)   NOT NULL,
    [ErrorType]                    VARCHAR (255)   NOT NULL,
    [SourceKey]                    INT             NOT NULL,
    [DimEffectiveDateID]           INT             NULL,
    [DimEffectiveTimeID]           INT             NULL,
    [DimFinancialTxDateID]         INT             NULL,
    [DimFinancialTxTimeID]         INT             NULL,
    [FinancialTxTypeSourceKey]     INT             NULL,
    [UserSourceKey]                INT             NULL,
    [ProcessEventSourceKey]        INT             NULL,
    [Reversed]                     BIT             NOT NULL,
    [RelatedFinancialTxSourceKey]  INT             NULL,
    [OriginalFinancialTxSourceKey] INT             NULL,
    [CurrencySourceKey]            INT             NULL,
    [TextDescription]              VARCHAR (100)   NULL,
    [FinancialTx_Amount]           DECIMAL (18, 2) NULL,
    [ExchangeRate]                 DECIMAL (16, 4) NULL,
    [ExternalReferenceNumber]      VARCHAR (100)   NULL,
    [FinancialTx_Fee]              DECIMAL (18, 2) NULL,
    [ForeignCurrencyAmount]        DECIMAL (18, 2) NULL,
    [ReferenceNumber]              VARCHAR (50)    NULL,
    [ShortCode]                    VARCHAR (10)    NULL,
    [Cancelled]                    BIT             NULL,
    [IsIntegrationTx]              BIT             NULL,
    [IntegrationTxSourceKey]       INT             NULL,
    [SYS_CHANGE_VERSION]           BIGINT          NOT NULL,
    [SYS_CHANGE_OPERATION]         CHAR (1)        NOT NULL
);

