CREATE TABLE [Errors].[Shared_FactProcessEvent] (
    [QueueID]                             INT             NOT NULL,
    [SSISErrorCode]                       INT             NOT NULL,
    [SSISErrorColumn]                     INT             NOT NULL,
    [PackageName]                         VARCHAR (255)   NOT NULL,
    [ErrorType]                           VARCHAR (255)   NOT NULL,
    [SourceKey]                           INT             NOT NULL,
    [ProcessTypeSourceKey]                INT             NULL,
    [UserSourceKey]                       INT             NULL,
    [ForUserSourceKey]                    INT             NULL,
    [ToUserSourceKey]                     INT             NULL,
    [InitiatingUserSourceKey]             INT             NULL,
    [ProcessChannelSourceKey]             INT             NOT NULL,
    [RequestedProcessChannelSourceKey]    INT             NULL,
    [ProcessStatusSourceKey]              INT             NULL,
    [HasFinancialTransaction]             BIT             NULL,
    [DimStartedDateID]                    INT             NULL,
    [DimStartedTimeID]                    INT             NULL,
    [DimCompletedDateID]                  INT             NULL,
    [DimCompletedTimeID]                  INT             NULL,
    [ProcessAmount]                       DECIMAL (18, 2) NULL,
    [ProcessFee]                          DECIMAL (18, 2) NULL,
    [AgentCommissionTypeSourceKey]        INT             NULL,
    [AgentCommissionAmount]               DECIMAL (18, 2) NULL,
    [ProcessCode]                         VARCHAR (36)    NOT NULL,
    [WithdrawalCode]                      VARCHAR (200)   NULL,
    [ATMReferenceNumber]                  VARCHAR (200)   NULL,
    [CardProcessorName]                   VARCHAR (200)   NULL,
    [CustomerBillerAccount]               VARCHAR (200)   NULL,
    [CustomerPhoneNumber]                 VARCHAR (200)   NULL,
    [DepositNumber]                       VARCHAR (200)   NULL,
    [LinkedPhoneNumber]                   VARCHAR (200)   NULL,
    [MerchantConfirmationCode]            VARCHAR (200)   NULL,
    [MerchantCustomerAccountNumber]       VARCHAR (200)   NULL,
    [PaymentSource]                       VARCHAR (200)   NULL,
    [ReferenceNumber]                     VARCHAR (200)   NULL,
    [SenderPhoneNumber]                   VARCHAR (200)   NULL,
    [DependentProcessEventSourceKey]      INT             NULL,
    [OriginalProcessEventSourceKey]       INT             NULL,
    [VerificationStatus]                  VARCHAR (200)   NULL,
    [ApprovedByUserSourceKey]             INT             NULL,
    [VerifiedByUserSourceKey]             INT             NULL,
    [CancellationApprovedByUserSourceKey] INT             NULL,
    [IntegrationReferenceNumber]          VARCHAR (200)   NULL,
    [SYS_CHANGE_VERSION]                  BIGINT          NOT NULL,
    [SYS_CHANGE_OPERATION]                CHAR (1)        NOT NULL
);

