CREATE TABLE [Errors].[Shared_DimDate] (
    [QueueID]               INT           NOT NULL,
    [SSISErrorCode]         INT           NOT NULL,
    [SSISErrorColumn]       INT           NOT NULL,
    [PackageName]           VARCHAR (255) NOT NULL,
    [ErrorType]             VARCHAR (255) NOT NULL,
    [DateID]                INT           NOT NULL,
    [Date]                  DATETIME      NOT NULL,
    [Day]                   INT           NOT NULL,
    [DaySuffix]             CHAR (3)      NOT NULL,
    [USDayOfWeek]           VARCHAR (9)   NOT NULL,
    [DayOfWeek]             VARCHAR (9)   NOT NULL,
    [DOWInMonth]            INT           NOT NULL,
    [DayOfYear]             INT           NOT NULL,
    [WeekOfYear]            INT           NOT NULL,
    [WeekOfMonth]           INT           NOT NULL,
    [MonthNumber]           INT           NOT NULL,
    [MonthName]             VARCHAR (9)   NOT NULL,
    [Quarter]               INT           NOT NULL,
    [QuarterName]           VARCHAR (255) NOT NULL,
    [YearName]              CHAR (4)      NOT NULL,
    [YearNumber]            INT           NOT NULL,
    [StandardDate]          VARCHAR (10)  NULL,
    [IsPublicHoliday]       BIT           NULL,
    [HolidayText]           VARCHAR (50)  NULL,
    [FinancialYearNumber]   INT           NOT NULL,
    [FinancialYearName]     CHAR (7)      NOT NULL,
    [FinancialPeriodNumber] INT           NOT NULL,
    [FinancialPeriodName]   VARCHAR (50)  NOT NULL,
    [Version]               INT           NOT NULL,
    [SYS_CHANGE_VERSION]    BIGINT        NOT NULL,
    [SYS_CHANGE_OPERATION]  CHAR (1)      NOT NULL
);

