CREATE TABLE [Errors].[Shared_DimPagaAccount] (
    [QueueID]                    INT           NOT NULL,
    [SSISErrorCode]              INT           NOT NULL,
    [SSISErrorColumn]            INT           NOT NULL,
    [PackageName]                VARCHAR (255) NOT NULL,
    [ErrorType]                  VARCHAR (255) NOT NULL,
    [SourceKey]                  INT           NOT NULL,
    [Name]                       VARCHAR (255) NOT NULL,
    [PagaAccountStatusSourceKey] INT           NOT NULL,
    [DimCreatedDateID]           INT           NOT NULL,
    [DimRegistrationDateID]      INT           NULL,
    [PagaAccountNumber]          VARCHAR (12)  NULL,
    [ExternalAccountNumber]      VARCHAR (12)  NULL,
    [BankingStatus]              VARCHAR (50)  NOT NULL,
    [hasOnlineAccount]           BIT           NULL,
    [IsActivePagaAccount]        BIT           NULL,
    [IsEnabled]                  BIT           NULL,
    [IsAffiliate]                BIT           NULL,
    [IsAgent]                    BIT           NULL,
    [IsBank]                     BIT           NULL,
    [IsBusiness]                 BIT           NULL,
    [IsCardProcessor]            BIT           NULL,
    [IsCashCollector]            BIT           NULL,
    [IsCustomer]                 BIT           NULL,
    [IsMerchant]                 BIT           NULL,
    [IsMobileOperator]           BIT           NULL,
    [IsPaga]                     BIT           NULL,
    [IsRemittanceProcessor]      BIT           NULL,
    [IsServiceAggregator]        BIT           NULL,
    [SYS_CHANGE_VERSION]         BIGINT        NOT NULL,
    [SYS_CHANGE_OPERATION]       CHAR (1)      NOT NULL
);

