CREATE TABLE [Activity].[FactProcessTx] (
    [FactProcessTxID] INT NOT NULL,
	[SourceKey] [int] NOT NULL,
	[DimCreatedDateID] INT NOT NULL,
	[DimCreatedTimeID] INT NOT NULL,
	[DimStartedDateID] INT NOT NULL,
	[DimStartedTimeID] INT NOT NULL,
	[DimCompletedDateID] INT NULL,
	[DimCompletedTimeID] INT NULL,
	[DimInitiatingUserID] [int] NULL,
	[DimOnBehalffUserID] [int] NULL,
	[DimReceivingUserID] [int] NULL,
	[DimOrganizationUnitLevel4ID] INT NULL,
	[DimChannelID] INT NOT NULL,
	[DimProcessStatusID] INT NOT NULL,
	[DimProcessTypeID] INT NOT NULL,
	[DimAgentCommissionTypeID]INT SPARSE NULL,
	[ProcessAmount] [decimal](18, 2) NULL,
	[ProcessFee] [decimal](18, 2) NULL,
	[AgentCommissionAmount] [decimal](18, 2) SPARSE NULL,
	[ProcessCode] [varchar](36) NOT NULL,
	[WithdrawalCode] [varchar](200) SPARSE NULL,
	[ATMReferenceNumber] [varchar](200) SPARSE NULL,
	[CardProcessorName] [varchar](200) SPARSE NULL,
	[CustomerBillerAccount] [varchar](200)SPARSE NULL,
	[CustomerPhoneNumber] [varchar](200) SPARSE NULL,
	[DepositNumber] [varchar](200) SPARSE NULL,
	[LinkedPhoneNumber] [varchar](200) SPARSE NULL,
	[MerchantConfirmationCode] [varchar](200) SPARSE NULL,
	[MerchantCustomerAccountNumber] [varchar](200) SPARSE  NULL,
	[PaymentSource] [varchar](200) SPARSE NULL,
	[ReferenceNumber] [varchar](200) SPARSE NULL,
	[SenderPhoneNumber] [varchar](200) SPARSE NULL,
	[DependentFactProcessTxID] INT SPARSE NULL,
	[OriginalFactProcessTxID] INT SPARSE NULL,
	[DimPagaAccountID] INT SPARSE NULL,
	[VerificationStatus] [varchar](200) SPARSE NULL,
	[DimApprovedByUserID] INT SPARSE NULL,
	[DimVerifiedByUserID] INT SPARSE NULL,
	[DimCancellationApprovedByUserID] INT SPARSE NULL,
	[IntegrationReferenceNumber] [varchar](200)SPARSE  NULL,
    CONSTRAINT [pk_FactProcessTxID] PRIMARY KEY CLUSTERED ([FactProcessTxID] ASC),
    CONSTRAINT [fk_FactProcessTx_DependentProcessID] FOREIGN KEY ([DependentFactProcessTxID]) REFERENCES [Activity].[FactProcessTx] ([FactProcessTxID]),
    CONSTRAINT [fk_FactProcessTx_DimAgentCommissionTypeID] FOREIGN KEY ([DimAgentCommissionTypeID]) REFERENCES [Classification].[DimAgentCommissionType] ([DimAgentCommissionTypeID]),
    CONSTRAINT [fk_FactProcessTx_DimApprovedByUserID] FOREIGN KEY ([DimApprovedByUserID]) REFERENCES [Shared].[DimUser] ([DimUserID]),
    CONSTRAINT [fk_FactProcessTx_DimCancellationApprovedByUserID] FOREIGN KEY ([DimCancellationApprovedByUserID]) REFERENCES [Shared].[DimUser] ([DimUserID]),
    CONSTRAINT [fk_FactProcessTx_DimChannelID] FOREIGN KEY ([DimChannelID]) REFERENCES [Activity].[DimChannel] ([DimChannelID]),
    CONSTRAINT [fk_FactProcessTx_DimCompletedDateID] FOREIGN KEY ([DimCompletedDateID]) REFERENCES [Shared].[DimDate] ([DimDateID]),
    CONSTRAINT [fk_FactProcessTx_DimCompletedTimeID] FOREIGN KEY ([DimCompletedTimeID]) REFERENCES [Shared].[DimTime] ([DimTimeID]),
    CONSTRAINT [fk_FactProcessTx_DimCreatedDateID] FOREIGN KEY ([DimCreatedDateID]) REFERENCES [Shared].[DimDate] ([DimDateID]),
    CONSTRAINT [fk_FactProcessTx_DimCreatedTimeID] FOREIGN KEY ([DimCreatedTimeID]) REFERENCES [Shared].[DimTime] ([DimTimeID]),
    CONSTRAINT [fk_FactProcessTx_DimInitiatingUserID] FOREIGN KEY ([DimInitiatingUserID]) REFERENCES [Shared].[DimUser] ([DimUserID]),
    CONSTRAINT [fk_FactProcessTx_DimOnBehalffUserID] FOREIGN KEY ([DimOnBehalffUserID]) REFERENCES [Shared].[DimUser] ([DimUserID]),
    CONSTRAINT [fk_FactProcessTx_DimOrganizationID] FOREIGN KEY ([DimOrganizationUnitLevel4ID]) REFERENCES shared.[DimOrganizationUnitLevel4] ([DimOrganizationUnitLevel4ID]),
    CONSTRAINT [fk_FactProcessTx_DimPagaAccountID] FOREIGN KEY ([DimPagaAccountID]) REFERENCES [Shared].[DimPagaAccount] ([DimPagaAccountID]),
    CONSTRAINT [fk_FactProcessTx_DimProcessStatusID] FOREIGN KEY ([DimProcessStatusID]) REFERENCES [Classification].[DimProcessStatus] ([DimProcessStatusID]),
    CONSTRAINT [fk_FactProcessTx_DimProcessTypeID] FOREIGN KEY ([DimProcessTypeID]) REFERENCES [Classification].[DimProcessType] ([DimProcessTypeID]),
    CONSTRAINT [fk_FactProcessTx_DimReceivingUserID] FOREIGN KEY ([DimReceivingUserID]) REFERENCES [Shared].[DimUser] ([DimUserID]),
    CONSTRAINT [fk_FactProcessTx_DimStartedDateID] FOREIGN KEY ([DimStartedDateID]) REFERENCES [Shared].[DimDate] ([DimDateID]),
    CONSTRAINT [fk_FactProcessTx_DimStartedTimeID] FOREIGN KEY ([DimStartedTimeID]) REFERENCES [Shared].[DimTime] ([DimTimeID]),
    CONSTRAINT [fk_FactProcessTx_DimVerifiedByUserID] FOREIGN KEY ([DimVerifiedByUserID]) REFERENCES [Shared].[DimUser] ([DimUserID]),
    CONSTRAINT [fk_FactProcessTx_OriginalProcessID] FOREIGN KEY ([OriginalFactProcessTxID]) REFERENCES [Activity].[FactProcessTx] ([FactProcessTxID])
);




GO
