//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphelion.FileImport.WindowsTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Dropbox (PW South Africa)\\Clients\\BIServices_Nigeria\\Pagatech\\R02_Recon\\Recon " +
            "Processes\\Bank Recon\\RawBankDownloads\\Skye_116738_1408443339269.CSV")]
        public string txtFileName_Text {
            get {
                return ((string)(this["txtFileName_Text"]));
            }
            set {
                this["txtFileName_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sql2012;Initial Catalog=PagaRecon;Integrated Security=True")]
        public string txtConn_Text {
            get {
                return ((string)(this["txtConn_Text"]));
            }
            set {
                this["txtConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyeImportHeader")]
        public string txtSectionCode_Text {
            get {
                return ((string)(this["txtSectionCode_Text"]));
            }
            set {
                this["txtSectionCode_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string txtStartRow_Text {
            get {
                return ((string)(this["txtStartRow_Text"]));
            }
            set {
                this["txtStartRow_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staging")]
        public string txtSchema_Text {
            get {
                return ((string)(this["txtSchema_Text"]));
            }
            set {
                this["txtSchema_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyeImportDetails")]
        public string txtTable_Text {
            get {
                return ((string)(this["txtTable_Text"]));
            }
            set {
                this["txtTable_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyeImportDetail")]
        public string txtSectionCodeDest_Text {
            get {
                return ((string)(this["txtSectionCodeDest_Text"]));
            }
            set {
                this["txtSectionCodeDest_Text"] = value;
            }
        }
    }
}
