CREATE TABLE [Errors].[FactMonthlyGLSnapshot] (
    [QueueID]                           INT             NOT NULL,
    [ErrorCode]                         INT             NOT NULL,
    [ErrorColumn]                       INT             NOT NULL,
    [PackageName]                       VARCHAR (255)   NOT NULL,
    [FactMonthlyGLSnapshotID]           INT             NULL,
    [AggregatedCreditAmount]            DECIMAL (18, 2) NULL,
    [AggregatedDebitAmount]             DECIMAL (18, 2) NULL,
    [CitySourceKey]                     VARCHAR (255)   NULL,
    [ClosingBalance]                    DECIMAL (18, 2) NULL,
    [CreditTransactionCount]            DECIMAL (18, 2) NULL,
    [DateSourceKey]                     VARCHAR (255)   NULL,
    [DebitTransactionCount]             DECIMAL (18, 2) NULL,
    [FinancialAccountSourceKey]         VARCHAR (255)   NULL,
    [FinancialTransactionTypeSourceKey] VARCHAR (255)   NULL,
    [MovementDirection]                 DECIMAL (18, 2) NULL,
    [OpeningBalance]                    DECIMAL (18, 2) NULL,
    [OrganizationUnitLevel5SourceKey]   VARCHAR (255)   NULL,
    [RunID]                             INT             NOT NULL,
    [DimAsOfDateID]                     INT             NULL,
    [DimCityID]                         INT             NULL,
    [DimFinancialAccountID]             INT             NULL,
    [DimFinancialTransactionTypeID]     INT             NULL,
    [DimOrganizationUnitLevel5ID]       INT             NULL
);

