CREATE TABLE [Errors].[FactProcessTransaction] (
    [QueueID]                         INT             NOT NULL,
    [ErrorCode]                       INT             NOT NULL,
    [ErrorColumn]                     INT             NOT NULL,
    [PackageName]                     VARCHAR (255)   NOT NULL,
    [FactProcessTransactionID]        INT             NULL,
    [AgentCommissionAmount]           DECIMAL (18, 2) NULL,
    [AgentCommissionTypeSourceKey]    VARCHAR (255)   NULL,
    [ApprovedByUserSourceKey]         VARCHAR (255)   NULL,
    [ATMReferenceNumber]              VARCHAR (255)   NULL,
    [BillerAccountUserSourceKey]      VARCHAR (255)   NULL,
    [CardProcessorName]               VARCHAR (255)   NULL,
    [ChannelSourceKey]                VARCHAR (255)   NULL,
    [CitySourceKey]                   VARCHAR (255)   NULL,
    [CompletedDateSourceKey]          VARCHAR (255)   NULL,
    [CompletedTimeSourceKey]          VARCHAR (255)   NULL,
    [CreatedDateSourceKey]            VARCHAR (255)   NULL,
    [CreatedTimeSourceKey]            VARCHAR (255)   NULL,
    [CustomerBillerAccount]           VARCHAR (255)   NULL,
    [CustomerPhoneNumber]             VARCHAR (255)   NULL,
    [DependentProcessID]              INT             NULL,
    [DepositNumber]                   VARCHAR (255)   NULL,
    [DimOriginalPayerPagaAccountIDID] INT             NULL,
    [DimPagaAccountID]                INT             NULL,
    [LinkedPhoneNumber]               VARCHAR (255)   NULL,
    [MerchantConfirmationCode]        VARCHAR (255)   NULL,
    [MerchantCustomerAccountNumber]   VARCHAR (255)   NULL,
    [OrganizationSourceKey]           VARCHAR (255)   NULL,
    [OrganizationUnitLevel5SourceKey] VARCHAR (255)   NULL,
    [OriginalProcessID]               INT             NULL,
    [PaymentSource]                   VARCHAR (255)   NULL,
    [ProcessAmount]                   DECIMAL (18, 2) NULL,
    [ProcessFee]                      DECIMAL (18, 2) NULL,
    [ProcessStatusSourceKey]          VARCHAR (255)   NULL,
    [ProcessTypeSourceKey]            VARCHAR (255)   NULL,
    [ReferenceNumber]                 VARCHAR (255)   NULL,
    [RequestedProcessChannel]         VARCHAR (255)   NULL,
    [RunID]                           INT             NOT NULL,
    [SenderPhoneNumber]               VARCHAR (255)   NULL,
    [StartedDateSourceKey]            VARCHAR (255)   NULL,
    [StartedTimeSourceKey]            VARCHAR (255)   NULL,
    [TransferDateSourceKey]           VARCHAR (255)   NULL,
    [TransferTimeSourceKey]           VARCHAR (255)   NULL,
    [UserSourceKey]                   VARCHAR (255)   NULL,
    [VerifiedByUserSourceKey]         VARCHAR (255)   NULL,
    [WithdrawalCode]                  VARCHAR (255)   NULL,
    [DimAgentCommissionTypeID]        INT             NULL,
    [DimApprovedByUserID]             INT             NULL,
    [DimBillerAccountUserID]          INT             NULL,
    [DimCancellationApprovedByUserID] INT             NULL,
    [DimChannelID]                    INT             NULL,
    [DimCityID]                       INT             NULL,
    [DimCompletedDateID]              INT             NULL,
    [DimCompletedTimeID]              INT             NULL,
    [DimCreatedDateID]                INT             NULL,
    [DimCreatedTimeID]                INT             NULL,
    [DimInitiatingUserID]             INT             NULL,
    [DimOnBehalffUserID]              INT             NULL,
    [DimOrganizationID]               INT             NULL,
    [DimOrganizationUnitLevel5ID]     INT             NULL,
    [DimProcessStatusID]              INT             NULL,
    [DimProcessTypeID]                INT             NULL,
    [DimReceivingUserID]              INT             NULL,
    [DimStartedDateID]                INT             NULL,
    [DimStartedTimeID]                INT             NULL,
    [DimTransferDateID]               INT             NULL,
    [DimTransferTimeID]               INT             NULL,
    [DimVerifiedByUserID]             INT             NULL
);

