CREATE TABLE [Errors].[FactFinancialTransactions] (
    [QueueID]                           INT             NOT NULL,
    [ErrorCode]                         INT             NOT NULL,
    [ErrorColumn]                       INT             NOT NULL,
    [PackageName]                       VARCHAR (255)   NOT NULL,
    [FactFinancialTransactionsID]       INT             NULL,
    [CitySourceKey]                     VARCHAR (255)   NULL,
    [CreatedDateSourceKey]              VARCHAR (255)   NULL,
    [CreatedTimeSourceKey]              VARCHAR (255)   NULL,
    [CreditAmount]                      DECIMAL (18, 2) NULL,
    [DebitAmount]                       DECIMAL (18, 2) NULL,
    [DimPagaAccountID]                  INT             NULL,
    [EffectiveDateSourceKey]            VARCHAR (255)   NULL,
    [EffectiveTimeSourceKey]            VARCHAR (255)   NULL,
    [FinancialAccountSourceKey]         VARCHAR (255)   NULL,
    [FinancialTransactionTypeSourceKey] VARCHAR (255)   NULL,
    [OrganizationUnitLevel5SourceKey]   VARCHAR (255)   NULL,
    [OriginalTransactionID]             INT             NULL,
    [ProcessTypeSourceKey]              VARCHAR (255)   NULL,
    [RelatedTransactionID]              INT             NULL,
    [RunID]                             INT             NOT NULL,
    [TransactionDateSourceKey]          VARCHAR (255)   NULL,
    [TransactionTimeSourceKey]          VARCHAR (255)   NULL,
    [UserSourceKey]                     VARCHAR (255)   NULL,
    [DimCityID]                         INT             NULL,
    [DimCreatedDateID]                  INT             NULL,
    [DimCreatedTimeID]                  INT             NULL,
    [DimEffectiveDateID]                INT             NULL,
    [DimEffectiveTimeID]                INT             NULL,
    [DimFinancialAccountID]             INT             NULL,
    [DimFinancialTransactionTypeID]     INT             NULL,
    [DimOrganizationUnitLevel5ID]       INT             NULL,
    [DimProcessTypeID]                  INT             NULL,
    [DimTransactionDateID]              INT             NULL,
    [DimTransactionTimeID]              INT             NULL,
    [DimUserID]                         INT             NULL
);

