CREATE TABLE [Errors].[Finance_FactFinancialTxHeader] (
    [QueueID]                                 INT             NOT NULL,
    [SSISErrorCode]                           INT             NOT NULL,
    [SSISErrorColumn]                         INT             NOT NULL,
    [PackageName]                             VARCHAR (255)   NOT NULL,
    [ErrorType]                               VARCHAR (255)   NOT NULL,
    [Amount]                                  DECIMAL (18, 2) NULL,
    [change_operation]                        CHAR (1)        NOT NULL,
    [DimCreatedDateID]                        INT             NOT NULL,
    [DimCreatedTimeID]                        INT             NOT NULL,
    [DimCurrencySourceKey]                    VARCHAR (255)   NULL,
    [DimEffectiveDateID]                      INT             NOT NULL,
    [DimEffectiveTimeID]                      INT             NOT NULL,
    [DimFinancialTransactionSubTypeSourceKey] VARCHAR (255)   NULL,
    [DimFinancialTransactionTypeSourceKey]    VARCHAR (255)   NOT NULL,
    [DimOrganizationUnitLevel4SourceKey]      VARCHAR (255)   NULL,
    [DimTransactionDateID]                    INT             NOT NULL,
    [DimTransactionTimeID]                    INT             NOT NULL,
    [DimUserSourceKey]                        VARCHAR (255)   NULL,
    [ExchangeRate]                            DECIMAL (16, 4) NULL,
    [ExternalReferenceNumber]                 VARCHAR (100)   NULL,
    [FactProcessTxSourceKey]                  INT             NOT NULL,
    [Fee]                                     DECIMAL (18, 2) NULL,
    [ForeignCurrencyAmount]                   DECIMAL (18, 2) NULL,
    [OriginalFactFinancialTxHeaderSourceKey]  INT             NULL,
    [ReferenceNumber]                         VARCHAR (50)    NULL,
    [RelatedFactFinancialTxHeaderSourceKey]   INT             NULL,
    [ShortCode]                               VARCHAR (10)    NOT NULL,
    [SourceKey]                               INT             NOT NULL,
    [TextDescription]                         VARCHAR (100)   NOT NULL
);

