CREATE TABLE [Staging].[Activity_FactProcessTransaction] (
    [DimCreatedDateID]                     INT             NULL,
    [DimCreatedTimeID]                     INT             NULL,
    [PagaAccountSourceKey]                 VARCHAR (255)   NULL,
    [ProcessTypeSourceKey]                 VARCHAR (255)   NULL,
    [AgentCommissionTypeSourceKey]         VARCHAR (255)   NULL,
    [InitiatingUserSourceKey]              VARCHAR (255)   NULL,
    [ReceivingUserSourceKey]               VARCHAR (255)   NULL,
    [OnBehalffUserSourceKey]               VARCHAR (255)   NULL,
    [ChannelSourceKey]                     VARCHAR (255)   NULL,
    [DimStartedDateID]                     INT             NULL,
    [DimStartedTimeID]                     INT             NULL,
    [DimCompletedDateID]                   INT             NULL,
    [DimCompletedTimeID]                   INT             NULL,
    [ProcessStatusSourceKey]               VARCHAR (255)   NULL,
    [BillerAccountUserSourceKey]           VARCHAR (255)   NULL,
    [OrganizationSourceKey]                VARCHAR (255)   NULL,
    [OriginalPayerPagaAccountSourceKey]    VARCHAR (255)   NULL,
    [DimTransferDateID]                    INT             NULL,
    [DimTransferTimeID]                    INT             NULL,
    [ApprovedByUserSourceKey]              VARCHAR (255)   NULL,
    [VerifiedByUserSourceKey]              VARCHAR (255)   NULL,
    [CancellationApprovedByUserSourceKey]  VARCHAR (255)   NULL,
    [OriginalProcessTransactionSourceKey]  VARCHAR (255)   NULL,
    [DependentProcessTransactionSourceKey] VARCHAR (255)   NULL,
    [ProcessTransactionSourceKey]          VARCHAR (255)   NOT NULL,
    [RequestedProcessChannel]              VARCHAR (255)   NULL,
    [CustomerPhoneNumber]                  VARCHAR (255)   NULL,
    [SenderPhoneNumber]                    VARCHAR (255)   NULL,
    [LinkedPhoneNumber]                    VARCHAR (255)   NULL,
    [ReferenceNumber]                      VARCHAR (255)   NULL,
    [ATMReferenceNumber]                   VARCHAR (255)   NULL,
    [DepositNumber]                        VARCHAR (255)   NULL,
    [MerchantCustomerAccountNumber]        VARCHAR (255)   NULL,
    [MerchantConfirmationCode]             VARCHAR (255)   NULL,
    [CardProcessorName]                    VARCHAR (255)   NULL,
    [PaymentSource]                        VARCHAR (255)   NULL,
    [CustomerBillerAccount]                VARCHAR (255)   NULL,
    [WithdrawalCode]                       VARCHAR (255)   NULL,
    [ProcessFee]                           DECIMAL (18, 2) NULL,
    [ProcessAmount]                        DECIMAL (18, 2) NULL,
    [AgentCommissionAmount]                DECIMAL (18, 2) NULL,
    [change_operation]                     CHAR (1)        NULL
);





