CREATE TABLE [Staging].[Activity_FactProcessTransaction] (
    [DimCreatedDateID]                     INT             NULL,
    [DimCreatedTimeID]                     INT             NULL,
    [PagaAccountSourceKey]                 INT             NULL,
    [ProcessTypeSourceKey]                 INT             NULL,
    [AgentCommissionTypeSourceKey]         INT             NULL,
    [InitiatingUserSourceKey]              INT             NULL,
    [ReceivingUserSourceKey]               INT             NULL,
    [OnBehalffUserSourceKey]               INT             NULL,
    [ChannelSourceKey]                     INT             NULL,
    [DimStartedDateID]                     INT             NULL,
    [DimStartedTimeID]                     INT             NULL,
    [DimCompletedDateID]                   INT             NULL,
    [DimCompletedTimeID]                   INT             NULL,
    [ProcessStatusSourceKey]               INT             NULL,
    [BillerAccountUserSourceKey]           INT             NULL,
    [OrganizationSourceKey]                INT             NULL,
    [OriginalPayerPagaAccountSourceKey]    INT             NULL,
    [DimTransferDateID]                    INT             NULL,
    [DimTransferTimeID]                    INT             NULL,
    [ApprovedByUserSourceKey]              INT             NULL,
    [VerifiedByUserSourceKey]              INT             NULL,
    [CancellationApprovedByUserSourceKey]  INT             NULL,
    [CitySourceKey]                        INT             NULL,
    [OriginalProcessTransactionSourceKey]  INT             NULL,
    [DependentProcessTransactionSourceKey] INT             NULL,
    [ProcessTransactionSourceKey]          INT             NOT NULL,
    [RequestedProcessChannel]              VARCHAR (255)   NULL,
    [CustomerPhoneNumber]                  VARCHAR (255)   NULL,
    [SenderPhoneNumber]                    VARCHAR (255)   NULL,
    [LinkedPhoneNumber]                    VARCHAR (255)   NULL,
    [ReferenceNumber]                      VARCHAR (255)   NULL,
    [ATMReferenceNumber]                   VARCHAR (255)   NULL,
    [DepositNumber]                        VARCHAR (255)   NULL,
    [MerchantCustomerAccountNumber]        VARCHAR (255)   NULL,
    [MerchantConfirmationCode]             VARCHAR (255)   NULL,
    [CardProcessorName]                    VARCHAR (255)   NULL,
    [PaymentSource]                        VARCHAR (255)   NULL,
    [CustomerBillerAccount]                VARCHAR (255)   NULL,
    [WithdrawalCode]                       VARCHAR (255)   NULL,
    [ProcessFee]                           DECIMAL (18, 2) NULL,
    [ProcessAmount]                        DECIMAL (18, 2) NULL,
    [AgentCommissionAmount]                DECIMAL (18, 2) NULL
);

